### ISSUE TITLE
Github says: forked from marcello3d/falcor-http-datasource

### ISSUE THREAD

**Issue by marcello3d** [Netflix/falcor-http-datasource#20]
<img width="870" alt="screen shot 2015-09-04 at 7 48 13 am" src="https://cloud.githubusercontent.com/assets/21952/9686549/57d6ab5e-52d9-11e5-9aa6-60a783beb19f.png">

Not sure how that happened... github bug?

**Comment by sdesai** [comment]
I'll follow up with them thanks. We restored it yesterday, and something may have gone wonky there.

**Comment by sdesai** [comment]
Fixed.
