### ISSUE TITLE
any plans for more resilient version then XmlHttp?

### ISSUE THREAD

**Issue by maksimlikharev** [Netflix/falcor-http-datasource#24]
any plans to use more sophisticated http client as a backing transport, like resilient or similar, spoiled by hystrix and ribbon in java, so this looks fragile.

**Comment by michaelbpaulson** [comment]
That could be done in a separate data source implementation.  This is purely relying HTTP for all the reliability concerns.  

Remember that a DataSource is just a contract in the end.  You can do whatever you want under the hood of a `get`, `set` and `call` functions. As long as they emit observables with JSONGraph, we are happy.

Feel free to create your own / extend this current one.
