### ISSUE TITLE
Npm released version does not sync with package.json

### ISSUE THREAD

**Issue by ratson** [Netflix/falcor-http-datasource#27]
The latest version on npm is `0.1.2`, but the version field in `package.json` is `0.1.1`

**Comment by ratson** [comment]
Is there any incompatible changes preventing `master` from releasing to `npm`?

https://github.com/Netflix/falcor-http-datasource/commit/ed25bd46adffd28fa35fc2d406a0a5f43c91ae2e
has fixed server-side usage, which is critical for my use case.

**Comment by michaelbpaulson** [comment]
This related to https://github.com/Netflix/falcor/issues/679

Essentially we need to release another version of this library.

**Comment by michaelbpaulson** [comment]
package json should be reved to 0.1.3 as there is a small bug fix.  We should also start generating changelogs.  But will do that for all future requests.

**Comment by michaelbpaulson** [comment]
npm is now in sync with 0.1.13.  Now its time to update falcor.
