### ISSUE TITLE
Attaching a subscription to the request fires the HTTP request multiple times

### ISSUE THREAD

**Issue by ekosz** [Netflix/falcor-http-datasource#28]
I have a custom data source that looks like this:

```js
function setLoaded() {
  // Do things
}

function noop() {}

class CustomSource extends HttpDataSource {
  get(...args) {
    const result = super.get(...args);
    result.subscribe(noop, noop, setLoaded);
    return result;
  }
}
```

But after adding that subscription, all of my network requests have been doubled.

<img width="854" alt="screen shot 2015-12-18 at 2 35 55 pm" src="https://cloud.githubusercontent.com/assets/212829/11908841/b4db0eea-a594-11e5-9b38-f7f99593adac.png">

Is this a bug with `falcor-http-datasource` or am I not subscribing correctly?

**Comment by michaelbpaulson** [comment]
@ekosz that is actually your bad on this one.  Remember Observables are _lazy_ and can be subscribed to multiple times. 

I am going to comment on your code.

```javascript
function setLoaded() {
  // Do things
}

function noop() {}

class CustomSource extends HttpDataSource {
  get(...args) {
    const result = super.get(...args);
    // You subscribe here, therefore the result._subscribe method is called (which does the HTTP request)
    result.subscribe(noop, noop, setLoaded);
   
    // Since this is a dataSource the Model "subscribes" to this observable to.
    return result;
  }
}
```

Instead it should look something like this.

```javascript
get: function getPaths(paths) {
    // If we don't we should consider exposing this "subscribable" interface
    const result = super.get(paths);
    return Observable.create(function(observer) {
        result.subscribe(
            observer.onNext.bind(observer),
            observer.onError.bind(observer),
            function customOnCompleted() {
                setLoaded();
                observer.onCompleted();
            }
    });
}
```

Hope that helps!  If it does please close the issue, if further explanation is needed, let me know.

**Comment by ekosz** [comment]
Okay that makes sense. Currently the `Observable` object isn't exposed by `falcor-http-datasource`. But basicly I just need to return something from this method that exposes a `subscribe` function.  Got it!
