### ISSUE TITLE
Requests have invalid url encoding

### ISSUE THREAD

**Issue by alexmuro** [Netflix/falcor-http-datasource#29]
My falcor router / virtual jsongraph lives inside an AWS Api Gateway endpoint and a lot of the paths generated by my client side falcor-http-datasource don't get routed because the url they generate is invalid because they include {} and ". I end up having to use the following as a work around:

```
class CustomSource extends HttpDataSource {
  onBeforeRequest (config) {
    config.url = config.url.replace(/"/g, "'")
    var splitUrl = config.url.split('?')
    config.url = splitUrl[0] + '?' + encodeURI(splitUrl[1])
  }
}
```
on the server side I switch back the single and double quotes before parsing the context.

All in all, this isn't a big deal but it would be nice if it worked out of the box with stricter URL parsers.

**Comment by michaelbpaulson** [comment]
This has been fixed in master this repo, just has not been released.  We will be releasing a new version shortly.

**Comment by alexmuro** [comment]
thanks for the info
